openapi: 3.0.0
info:
  title: E-commerce API
  description: API para gerenciamento de usuários
  version: 1.0.0

paths:
  /users:
    post:
      summary: Cria um novo usuário
      tags:
        - Usuários
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - name
                - email
                - password
      responses:
        '201':
          description: Usuário criado com sucesso
        '409':
          description: Email já está em uso
