openapi: 3.0.0
info:
  title: E-commerce API
  description: API para gerenciamento de usuários
  version: 1.0.0

paths:
  /users:
    post:
      summary: Cria um novo usuário
      tags:
        - Usuários
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - name
                - email
                - password
      responses:
        '201':
          description: Usuário criado com sucesso
        '409':
          description: Email já está em uso
  /auth/login:
    post:
      tags:
        - Auth
      summary: Realiza login e retorna um token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserDto'
      responses:
        '201':
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
        '401':
          description: Credenciais inválidas

components:
  schemas:
    CreateUserDto:
      type: object
      properties:
        name:
          type: string
          example: Bruno Silva
        email:
          type: string
          example: bruno@example.com
        password:
          type: string
          format: password
          example: 123456
      required:
        - name
        - email
        - password
    LoginUserDto:
      type: object
      properties:
        email:
          type: string
          example: user@example.com
        password:
          type: string
          example: 123456
      required:
        - email
        - password