openapi: 3.0.0
info:
  title: E-commerce API
  description: API para gerenciamento de usuários
  version: 1.0.0

paths:
  /users:
    post:
      summary: Cria um novo usuário
      tags:
        - Usuários
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - name
                - email
                - password
      responses:
        '201':
          description: Usuário criado com sucesso
        '409':
          description: Email já está em uso

  /users/me:
    patch:
      summary: Atualiza dados do usuário autenticado
      security:
        - bearerAuth: []
      tags:
        - Usuários
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "João da Silva"
                email:
                  type: string
                  example: "joao@example.com"
                password:
                  type: string
                  example: "NovaSenha@123"
      responses:
        '200':
          description: Usuário atualizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
                  updatedAt:
                    type: string
                    format: date-time
        '409':
          description: Email já está em uso
        '401':
          description: Não autorizado – token inválido ou ausente


  /auth/login:
    post:
      tags:
        - Auth
      summary: Realiza login e retorna um token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserDto'
      responses:
        '200':
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
        '401':
          description: Credenciais inválidas

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CreateUserDto:
      type: object
      properties:
        name:
          type: string
          example: Bruno Silva
        email:
          type: string
          example: bruno@example.com
        password:
          type: string
          format: password
          example: '@Pass.10'
      required:
        - name
        - email
        - password
    LoginUserDto:
      type: object
      properties:
        email:
          type: string
          example: user@example.com
        password:
          type: string
          example: '@Pass.10'
      required:
        - email
        - password